spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:19092,localhost:29092,localhost:39092
          autoAddPartitions: true
        bindings:
          input:
            consumer:
              enableDlq: true
      bindings:
        input:
          destination: dlq.destination
          group: dlq-app
          max-attempts: 1

        input-error:
          destination: error.dlq.destination.dlq-app
          group: dlq-app

server:
  port: 0
