spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:19092,localhost:29092,localhost:39092
          autoAddPartitions: true
        bindings:
          handleMessage-in-0:
            consumer:
              enableDlq: true

      bindings:
        handleMessage-in-0:
          destination: dlq.destination
          group: dlq-app
          max-attempts: 1

        handleError-in-0:
          destination: error.dlq.destination.dlq-app
          group: dlq-app

    function:
      definition: handleMessage;handleError

server:
  port: 0
