spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:19092,localhost:29092,localhost:39092
          autoAddPartitions: true
          minPartitionCount: 12
      bindings:
        input:
          destination: events.destination
          group: eventGroup
          consumer:
            concurrency: 12

server:
  port: 0
