spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:19092,localhost:29092,localhost:39092
          autoAddPartitions: true

      bindings:
        eventSupplier-out-0:
          destination: events.destination
          producer:
            partition-key-expression: payload.id
            #            partition-key-expression: payload.uuid
            partition-count: 12

      poller:
        max-messages-per-poll: 100

server:
  port: 0
