spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:19092,localhost:29092,localhost:39092
          autoAddPartitions: true
          minPartitionCount: 4
      bindings:
        input:
          destination: partitioned.destination
          group: myGroup
          consumer:
            concurrency: 4

server:
  port: 0
